# code taken from https://www.youtube.com/watch?v=WW6ZUw9IExA
name: Hello World

on:
  push:
    branches:
      - "main"
    pull_request:
      - "main"

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Hello Step
        run: echo "Hello World"
