# code taken from https://www.youtube.com/watch?v=WW6ZUw9IExA
name: Run tests

on:
  push:
    branches:
      - "main"
    pull_request:
      branches:
      - "main"

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.14.1
        - name: Install Dependencies
          run:  npm ci
        - name: Run tests
          run: npm test


